### ISSUE TITLE
Is it possible to custom train a model for LanceOtron?

### ISSUE THREAD

**Issue by mcsimenc** [LHentges/LanceOtron#16]
If so, how can it be done? Thanks!

**Comment by LHentges** [comment]
Unfortunately this isn't really a feature of LanceOtron, but it is something we're hoping to bring to the next version. 

Early on in development we had built a method for transfer learning - where the model starts with the trained weights and only modifies the output layers based on user identified regions/classifications. It was really difficult to connect with the web tool, especially since at the time the model was still being fine tuned, and ultimately it was scrapped for time.

In the future I'm not sure we would have it as part of the web tool at all, but create another module for training, either from scratch or with transfer learning, and wrap it with the command line tools.

Were you trying to train a new model from scratch or update the existing model? From scratch would take a fairly large dataset, on the order of thousands of samples per class, while transfer would be more like hundreds per class.

**Comment by mcsimenc** [comment]
Thanks for the explanation. I'd try transfer learning first and possibly from scratch if deemed necessary after examining the results.
